spring.application.name=web
spring.thymeleaf.cache=false

# Database configuration
spring.datasource.url=${DB_URL:jdbc:sqlite:./data/songs.sqlite}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:org.sqlite.JDBC}